### ISSUE TITLE
SceneItemProperties - Invalid Request Parameters

### ISSUE THREAD

**Issue by haganbmj** [Palakis/obs-websocket#217]
##### Issue type
Bug Report

##### Description
Unable to send `GetSceneItemProperties` or `SetSceneItemProperties`, appears to be related to parsing the incoming json structure as it passes the first check and recognizes at least the `item` top level object.

https://github.com/Palakis/obs-websocket/blob/e316da9b6ebd75985bae64f6245a8081ceee524a/src/WSRequestHandler_SceneItems.cpp#L43-L47

##### Steps to reproduce and other useful info
```js
obs.send('GetSceneItemProperties', { item: { name: 'Camera' } }).then(console.log).catch(console.error);
```

OBS Logs.
```
18:15:10.654: [obs-websocket] Request >> '{"item":{"name":"Camera"},"request-type":"GetSceneItemProperties","message-id":"1"}'
18:15:10.654: [obs-websocket] Response << '{
18:15:10.654:     "error": "invalid request parameters",
18:15:10.654:     "message-id": "1",
18:15:10.654:     "status": "error"
18:15:10.654: }'
```

##### Technical information
- **Operating System** : Windows 10
- **OBS Studio version** : 21.1.0, 64bit

```
18:13:05.599: [obs-websocket] you can haz websockets (version 4.3.3)
18:13:05.599: [obs-websocket] qt version (compile-time): 5.10.1 ; qt version (run-time): 5.10.1
```

Additional details in the original report.
https://github.com/haganbmj/obs-websocket-js/issues/105

**Comment by jellomold** [comment]
additional observations to haganbmj's comment.  the documentation makes reference to an unknown thing called a "item->id" but does suggest the id is the same as the name.   I'm super keen to get this working.  looking through the project's source code made me notice the obs_data_get_obj() function isn't called very often. Im' almost thinking it's the problem.  but how or why it's failing is yet tbd.

i'm grabbing qt and obslib etc..i'll work on it as well this week. try to debug it some more.

**Comment by macharborguy** [comment]
I too am running into this issue, with both SetSceneItemProperties as well as GetSceneItemProperties, making it impossible to actually use OBS-WebSockets for any source manipulation.

OBS Studio v21.1.2
obs-websocket v4.3.3
obs-websocket-js v1.2.0

**Comment by EmptySora** [comment]
It seems that for some reason this is fixed on the [4.x-current](https://github.com/Palakis/obs-websocket/blob/4.x-current/src/WSRequestHandler_SceneItems.cpp#L40-L44) branch, but not on the [master](https://github.com/Palakis/obs-websocket/blob/master/src/WSRequestHandler_SceneItems.cpp#L43-L47) branch.
If you either build from the 4.x-current branch or use the [installers/binaries](https://github.com/Palakis/obs-websocket/releases) it works just fine.
I haven't tested building the 4.x-current branch, however, I did install the 4.4.0 release using the [Windows installer](https://github.com/Palakis/obs-websocket/releases/download/4.4.0/obs-websocket-4.4.0-Windows-Installer.exe)
Running the following with obs-websocket-js work:
```js
obs.send('GetSceneItemProperties', { item: 'Camera' }).then(console.log).catch(console.error);
```
and
```js
obs.send('SetSceneItemProperties', { item: 'Camera', visible: true }).then(console.log).catch(console.error);
```
returns similar to:
```js
{
    "message-id": "16"
    messageId: "16"
    status: "ok"
}
```

Tested on:
- Operating System: Windows 10
- OBS Studio Version: 22.0.2 (64-bit)
- obs-websocket Version: 4.4.0
  - obs-websocket qt Version: (compile) 5.10.1; (runtime) 5.10.1
- obs-websocket-js Version: v1.2.0 [commit](https://github.com/haganbmj/obs-websocket-js/commit/5720c1fe1575a43fe99a624e1dc5b71a0217bbdd)

Does this count as being fixed...?

**Comment by sqr** [comment]
No matter how much I try, I still get errors trying to work with SetSceneItemProperties...

My code looks like this:

obs.send('SetSceneItemProperties', { 'scene-name' : 'Escena', 'item' : 'Imagen', 'position' : { 'x' : 300 } });

and I get this error

![image](https://user-images.githubusercontent.com/1871860/54526306-a8e41800-4976-11e9-92a3-f7cbee457f1b.png)


I am able to change the streaming server, HLS sources for streams and start and stop a stream, but changing size and scale of a layer is not working :/ Is there still a bug with SetSceneItemProperties or am I doing something wrong?

OBS 23.0.2
OBS Websocket 4.5.0 RC (Win installer)
obs-websocket-js 2.0.1

Thanks

**Comment by Palakis** [comment]
Just tested this, looks fixed in the latest 4.x-current.

**Comment by Palakis** [comment]
@haganbmj `item` is a string containing the scene item name, not an object. Would this mean there's been a docs/api breaking change?

**Comment by Palakis** [comment]
It's possible I screwed up a bit at some point when syncing between master and 4.x-current. Apologies for this.
