### ISSUE TITLE
TakeSourceScreenshot: "Unsupported picture format: jpg"

### ISSUE THREAD

**Issue by ethaniel** [Palakis/obs-websocket#351]
I can't get TakeSourceScreenshot to work.

If i do:
```
{"request-type": "TakeSourceScreenshot", "sourceName":"Main","saveToFilePath":"d:\youtube_thumb.jpg","message-id": "5"}
```

I get:

```
object(stdClass)#4 (3) {
  ["error"]=>
  string(17) "Image save failed"
  ["message-id"]=>
  string(1) "5"
  ["status"]=>
  string(5) "error"
}
```

If i do:
```
{"request-type": "TakeSourceScreenshot", "sourceName":"Main","embedPictureFormat":"jpg","message-id": "5"}
```

I get:

```
object(stdClass)#4 (3) {
  ["error"]=>
  string(31) "Unsupported picture format: jpg"
  ["message-id"]=>
  string(1) "5"
  ["status"]=>
  string(5) "error"
}
```

**Comment by Palakis** [comment]
@ethaniel Try using jpeg instead of jpg.

**Comment by ethaniel** [comment]
Same, even tried png.

**Comment by ethaniel** [comment]
Ok, so it was my mistake. Actually a bunch of mistakes:

1. I sent a Scene name instead of a Source name.
2. I sent $path (just the variable) instead of the actual path (i forgot that I was using single quotes instead of double quotes).

However, "embedPictureFormat":"jpg" doesn't work (I get "Unsupported picture format: jpg"). So I ended up sending "embedPictureFormat":"png" with a correct Source name and everything works now.

Sorry about this. I hope somebody finds this useful.

**Comment by ethaniel** [comment]
I'm going to reopen this ticket, because neither "jpg" nor "jpeg" formats work.

**Comment by Palakis** [comment]
Fixed in #437. Will be released with version 4.8.0

**Comment by vladkorotnev** [comment]
Sorry to necropost, but this still occurs for me no matter if `jpeg` or `jpg`. Does it have to deal with the particular version of OBS or Qt installed on the system?

Log snippet:

```
20:08:34.203: [obs-websocket] Request >> '{"message-id":"574","request-type":"TakeSourceScreenshot","embedPictureFormat":"jpg","compressQuality":50,"width":320}'
20:08:34.208: [obs-websocket] Response << '{
20:08:34.208:     "error": "unsupported picture format: jpg",
20:08:34.208:     "message-id": "574",
20:08:34.208:     "status": "error"
20:08:34.208: }'
...
20:09:18.830: CPU Name: Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz
20:09:18.830: CPU Speed: 1498MHz
20:09:18.830: Physical Cores: 4, Logical Cores: 8
20:09:18.830: Physical Memory: 16153MB Total, 8913MB Free
20:09:18.830: Windows Version: 10.0 Build 18363 (release: 1909; revision: 959; 64-bit)
20:09:18.830: Running as administrator: false
20:09:18.830: Aero is Enabled (Aero is always on for windows 8 and above)
20:09:18.830: Windows 10 Gaming Features:
20:09:18.830: 	Game Bar: On
20:09:18.830: 	Game DVR: On
20:09:18.830: 	Game DVR Background Recording: Off
20:09:18.831: Sec. Software Status:
20:09:18.832: 	Windows Defender Antivirus: enabled (AV)
20:09:18.833: 	Windows Firewall: enabled (FW)
20:09:18.833: Current Date/Time: 2021-03-23, 20:09:18
20:09:18.833: Browser Hardware Acceleration: true
20:09:18.833: Portable mode: false
20:09:19.133: OBS 26.1.1 (64-bit, windows)
20:09:19.133: ---------------------------------
20:09:19.134: ---------------------------------
20:09:19.134: audio settings reset:
20:09:19.134: 	samples per sec: 48000
20:09:19.134: 	speakers:        2
20:09:19.135: ---------------------------------
20:09:19.135: Initializing D3D11...
20:09:19.135: Available Video Adapters: 
20:09:19.137: 	Adapter 0: Intel(R) Iris(R) Plus Graphics
20:09:19.137: 	  Dedicated VRAM: 134217728
20:09:19.137: 	  Shared VRAM:    4174260224
20:09:19.137: 	  PCI ID:         8086:8a52
20:09:19.138: 	  Driver Version: 26.20.100.7463
20:09:19.138: 	  output 0: pos={0, 0}, size={2560, 1080}, attached=true, refresh=60, name=LG ULTRAWIDE
20:09:19.138: 	Adapter 1: NVIDIA GeForce GTX 1650 with Max-Q Design
20:09:19.138: 	  Dedicated VRAM: 4154458112
20:09:19.138: 	  Shared VRAM:    4174260224
20:09:19.138: 	  PCI ID:         10de:1f91
20:09:19.139: 	  Driver Version: 27.21.14.6140
20:09:19.142: Loading up D3D11 on adapter Intel(R) Iris(R) Plus Graphics (0)
20:09:19.160: D3D11 loaded successfully, feature level used: b000
20:09:19.160: DXGI increase maximum frame latency success
20:09:19.576: ---------------------------------
20:09:19.576: video settings reset:
20:09:19.576: 	base resolution:   1920x1080
20:09:19.576: 	output resolution: 1920x1080
20:09:19.576: 	downscale filter:  Bicubic
20:09:19.576: 	fps:               60/1
20:09:19.576: 	format:            NV12
20:09:19.576: 	YUV mode:          709/Partial
20:09:19.576: NV12 texture support enabled
20:09:19.576: Audio monitoring device:
20:09:19.576: 	name: Default
20:09:19.576: 	id: default
20:09:19.578: ---------------------------------
20:09:19.582: [CoreAudio encoder]: CoreAudio AAC encoder not installed on the system or couldn't be loaded
20:09:19.582: Failed to load 'en-US' text for module: 'decklink-captions.dll'
20:09:19.583: Failed to load 'en-US' text for module: 'decklink-ouput-ui.dll'
20:09:19.613: [AMF] Unable to load 'amfrt64.dll', error code 126.
20:09:19.615: [AMF] AMF Test failed due to one or more errors.
20:09:19.615: Failed to initialize module 'enc-amf.dll'
20:09:19.632: [obs-browser]: Version 2.9.1
20:09:19.632: [obs-browser]: CEF Version 75.1.16+g16a67c4+chromium-75.0.3770.100
20:09:19.632: [obs-browser]: Blacklisted device detected, disabling browser source hardware acceleration.
20:09:19.635: NVENC supported
20:09:19.651: [obs-websocket] you can haz websockets (version 4.9.0)
20:09:19.651: [obs-websocket] qt version (compile-time): 5.10.1 ; qt version (run-time): 5.15.2
20:09:19.653: [obs-websocket] module loaded!
...
20:09:30.076: [obs-websocket] Request >> '{"message-id":"2","request-type":"TakeSourceScreenshot","embedPictureFormat":"jpeg","compressQuality":50,"width":320}'
20:09:30.078: [obs-websocket] Response << '{
20:09:30.078:     "error": "unsupported picture format: jpeg",
20:09:30.078:     "message-id": "2",
20:09:30.078:     "status": "error"
20:09:30.078: }'
```
